### ISSUE TITLE
Procedure of Computing C(h)

### ISSUE THREAD

**Issue by jiaqingxie** [YilunKuang/token-bounds-for-llms#1]
Dear author, I just saw that you mentioned you used gzip to the quantized LLMs to get C(h). How to do this, thanks.

**Comment by YilunKuang** [comment]
Hi @jiaqingxie, thank you for your interest in our work! We will release the official code before the NeurIPS Conference date, but here is a code snippet for how to get C(h):

```bash
# single checkpoint file
gzip -c model.safetensors > model.safetensors.gz
ls -l model.safetensors.gz
```

You simply need to read off the number of bits needed to store `model.safetensors.gz` by inspecting the standard output of the `ls` command in a bash shell. Here is an example of the `model.safetensors.gz` file for the Llama-2 7B model quantized to 2 bits using QuIP# available in https://huggingface.co/relaxml/Llama-2-7b-E8P-2Bit/blob/main/model.safetensors. 

For a model whose weights are stored in multiple files, you can use the following command to get C(h):

```bash
# multiple checkpoint files
tar -czvf combined_checkpoint.tar.gz model-00001-of-00002.safetensors model-00002-of-00002.safetensors
ls -l combined_checkpoint.tar.gz
```

Here is an example of the Llama2-70B model quantized to 2 bits with multiple *.safetensors file for storing model weights: https://huggingface.co/relaxml/Llama-2-70b-E8P-2Bit/tree/main.

Let us know if you have any other questions! 

Best,
Yilun

**Comment by jiaqingxie** [comment]
Thanks. That helps.
